language: rust
sudo: required
dist: trusty

branches:
  except:
    - master

env:
  - CODECOV_TOKEN=4a860efa-08b5-48a1-a668-3772faf4534a

services:
  - docker

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo build
  - cargo clippy --all-targets
  - cargo test

after_success: |
  docker run --security-opt seccomp=unconfined    \
        -v "$(pwd):/volume"                       \
        xd009642/tarpaulin                        \
        cargo tarpaulin --out Xml
  case "$CODECOV_TOKEN" in
    '{'*)
        ;;
    *)
      bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage report to codecov.io"
        ;;
  esac
